crasterras/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('crop.urls')),
    path('admin/', admin.site.urls),
    path('sensor/', include('sensor.urls')),
]

crop/urls.py
from django.urls import path
from .views import CropView

urlpatterns = [
    path('', CropView.as_view(), name="index"),
]

sensor/urls.py
from django.urls import path
from .views import SensorDataApi

urlpatterns = [
    path('data/', SensorDataApi.as_view()),
]

crop/models.py
from django.db import models

#model sensor
from sensor.models import Sensor
TYPE_OF_CROP = (
    ('CHILE HABANERO', 'Chile habanero'),
    ('PAPAYA', 'Papaya'),
    ('LIMON', 'Limon')
)

# Create your models here.
class Crop(models.Model):
    name = models.CharField(max_length=200, verbose_name="Nombre del cultivo")
    type_crop = models.CharField(max_length=40, choices=TYPE_OF_CROP)
    sensor = models.ForeignKey(
        Sensor, verbose_name="Sensor", related_name="cultivo_sensor", on_delete=models.CASCADE)
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Crop"
        verbose_name_plural = "Crops"

    def __str__(self):
        return "{} {} {}".format(self.name, self.type_crop, self.created)

sensor/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Sensor(models.Model):
    user = models.ForeignKey(User, verbose_name="User", null=True,
                                blank=True, related_name="sensor_usuario", on_delete=models.CASCADE)
    latitude = models.FloatField(
        blank=True, null=True, verbose_name='Latitude')
    length = models.FloatField(
        blank=True, null=True, verbose_name='Length')
    imei = models.CharField(
        max_length=15, primary_key=True, verbose_name='IMEI')
    aggregate = models.BooleanField(default=False)
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Creation date")
    updated = models.DateTimeField(
        auto_now=True, verbose_name="Update date")

    class Meta:
        verbose_name = "Sensor"
        verbose_name_plural = "Sensors"

    def __str__(self):
        return "{}".format(self.imei)



class DataSensor(models.Model):
    sensor = models.OneToOneField(Sensor, verbose_name="Sensor",
                               related_name="datasensor_sensor", on_delete=models.CASCADE)
    db = models.FloatField(verbose_name="Db")
    voltage = models.FloatField(verbose_name="Voltaje")
    humidity_environmental = models.FloatField(
        verbose_name="Humedad ambiental")
    temperature_environmental = models.FloatField(
        verbose_name="Temperatura ambiental")
    ground_one_hum = models.FloatField(verbose_name="Suelo uno Humedad")
    ground_one_tem = models.FloatField(verbose_name="Suelo uno temperatura")
    ground_one_con = models.FloatField(verbose_name="Suelo uno conductividad")
    ground_two_hum = models.FloatField(verbose_name="Suelo dos humedad")
    ground_two_tem = models.FloatField(verbose_name="Suelo dos temperatura")
    ground_two_con = models.FloatField(verbose_name="Suelo dos conductividad")
    sheet_hum = models.FloatField(verbose_name="Hoja Humedad")
    sheet_temp = models.FloatField(verbose_name="Hoja temperatura")
    brightness = models.FloatField(verbose_name="Luminosidad")
    speed_wind = models.FloatField(verbose_name="Velocidad del viento")
    address_wind = models.CharField(
        max_length=10, verbose_name="Direccion del viento")
    radiation_solar = models.FloatField(verbose_name="Radiacion solar")
    created = models.DateTimeField(
        auto_now_add=True, verbose_name="Fecha de creación")

    class Meta:
        verbose_name = "Data Sensor"
        verbose_name_plural = "Data Sensors"

    def __str__(self):
        return "{}".format(self.sensor)

crop/views.py
from django.shortcuts import render

#libs
from django.views.generic import DetailView, ListView
# model
from .models import Crop


class CropView(ListView):
    model = Crop
    template_name = 'crop/index.html'

sensor/views.py
from django.shortcuts import render


# API
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import IsAuthenticated

# Models
from .models import DataSensor, Sensor

#Serializer
from .serializers import DataSensorSerializer


class SensorDataApi(CreateAPIView):
    permission_classes = (IsAuthenticated,)

    queryset = DataSensor.objects.all()
    serializer_class = DataSensorSerializer

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="h-100">
    <nav>
        
    </nav>
    <div class="container-fluid">
        <div class="row h-100 justify-content-center align-items-center largo">
            <div id="auth-container">
                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
    <!-- javascript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    {% block script_block %}{% endblock %}
</body>

</html>

templates/crop/index.html
{% extends "base.html" %}

{% block head_content %}
<title>Crasterras</title>
{% endblock %}
    
{% block container %}
{% load static %}
 <div class="row">
     <div class="col-lg-9">
        <a href="#">
            <img id="user-img" src="{% static 'img/user_proof.jpg' %}">
        </a>
         <div id="map"></div>
    </div>
    <div class="col-lg-3">
        {{crop_list.0.name}}<br>
        {{crop_list.0.sensor.latitude}}
    </div>
 </div>
{% endblock %}
{% block script_block %}
 <script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: { lat: 19.6930200, lng: -89.0503700 },
            zoom: 8,
            mapTypeId: 'hybrid',
            streetViewControl: false,
            mapTypeControl: false,
            fullscreenControl: false,
        });
        var uluru = {lat: 20.9621201, lng: -89.59549799999999}
        marker = new google.maps.Marker({
            icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',
            position: uluru,
            draggable: false,
            map: this.map 
        })
        marker.addListener('click', clickedCulture)
        function clickedCulture () {
            startMarkerAnimation(marker)
        }
        function startMarkerAnimation(marker) {
          if (marker.getAnimation() !== null) {
            marker.setAnimation(null)
          } else {
            marker.setAnimation(google.maps.Animation.BOUNCE)
          }
            return true
        }
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoKEVrCqMF3tRtAdswCrGKRe0Bz8drOv4&callback=initMap" async defer></script>
{% endblock %}